from pyspark.sql.types import *

schema_joined_source_detection = StructType(
    [
        StructField("sourceID", LongType(), True),
        StructField("cuEventID", IntegerType(), True),
        StructField("frameSetID", LongType(), True),
        StructField("ra", DoubleType(), True),
        StructField("dec", DoubleType(), True),
        StructField("cx", DoubleType(), True),
        StructField("cy", DoubleType(), True),
        StructField("cz", DoubleType(), True),
        StructField("htmID", LongType(), True),
        StructField("l", DoubleType(), True),
        StructField("b", DoubleType(), True),
        StructField("lambda", DoubleType(), True),
        StructField("eta", DoubleType(), True),
        StructField("priOrSec", LongType(), True),
        StructField("zmyPnt", DoubleType(), True),
        StructField("zmyPntErr", DoubleType(), True),
        StructField("ymjPnt", DoubleType(), True),
        StructField("ymjPntErr", DoubleType(), True),
        StructField("jmhPnt", DoubleType(), True),
        StructField("jmhPntErr", DoubleType(), True),
        StructField("hmksPnt", DoubleType(), True),
        StructField("hmksPntErr", DoubleType(), True),
        StructField("h_1mks_1Pnt", DoubleType(), True),
        StructField("h_1mks_1PntErr", DoubleType(), True),
        StructField("h_2mks_2Pnt", DoubleType(), True),
        StructField("h_2mks_2PntErr", DoubleType(), True),
        StructField("j_1mh_1Pnt", DoubleType(), True),
        StructField("j_1mh_1PntErr", DoubleType(), True),
        StructField("j_2mh_2Pnt", DoubleType(), True),
        StructField("j_2mh_2PntErr", DoubleType(), True),
        StructField("z_1my_1Pnt", DoubleType(), True),
        StructField("z_1my_1PntErr", DoubleType(), True),
        StructField("z_2my_2Pnt", DoubleType(), True),
        StructField("z_2my_2PntErr", DoubleType(), True),
        StructField("mergedClassStat", DoubleType(), True),
        StructField("mergedClass", ShortType(), True),
        StructField("pStar", DoubleType(), True),
        StructField("pGalaxy", DoubleType(), True),
        StructField("pNoise", DoubleType(), True),
        StructField("pSaturated", DoubleType(), True),
        StructField("zMjd", DoubleType(), True),
        StructField("zAperMag1", DoubleType(), True),
        StructField("zAperMag1Err", DoubleType(), True),
        StructField("zAperMag3", DoubleType(), True),
        StructField("zAperMag3Err", DoubleType(), True),
        StructField("zAperMag4", DoubleType(), True),
        StructField("zAperMag4Err", DoubleType(), True),
        StructField("zGausig", DoubleType(), True),
        StructField("zEll", DoubleType(), True),
        StructField("zPA", DoubleType(), True),
        StructField("zErrBits", IntegerType(), True),
        StructField("zAverageConf", DoubleType(), True),
        StructField("zClass", ShortType(), True),
        StructField("zClassStat", DoubleType(), True),
        StructField("zppErrBits", IntegerType(), True),
        StructField("zSeqNum", IntegerType(), True),
        StructField("zXi", DoubleType(), True),
        StructField("zEta", DoubleType(), True),
        StructField("z_1Mjd", DoubleType(), True),
        StructField("z_1AperMag1", DoubleType(), True),
        StructField("z_1AperMag1Err", DoubleType(), True),
        StructField("z_1AperMag3", DoubleType(), True),
        StructField("z_1AperMag3Err", DoubleType(), True),
        StructField("z_1AperMag4", DoubleType(), True),
        StructField("z_1AperMag4Err", DoubleType(), True),
        StructField("z_1Gausig", DoubleType(), True),
        StructField("z_1Ell", DoubleType(), True),
        StructField("z_1PA", DoubleType(), True),
        StructField("z_1ErrBits", IntegerType(), True),
        StructField("z_1AverageConf", DoubleType(), True),
        StructField("z_1Class", ShortType(), True),
        StructField("z_1ClassStat", DoubleType(), True),
        StructField("z_1ppErrBits", IntegerType(), True),
        StructField("z_1SeqNum", IntegerType(), True),
        StructField("z_1Xi", DoubleType(), True),
        StructField("z_1Eta", DoubleType(), True),
        StructField("z_2Mjd", DoubleType(), True),
        StructField("z_2AperMag1", DoubleType(), True),
        StructField("z_2AperMag1Err", DoubleType(), True),
        StructField("z_2AperMag3", DoubleType(), True),
        StructField("z_2AperMag3Err", DoubleType(), True),
        StructField("z_2AperMag4", DoubleType(), True),
        StructField("z_2AperMag4Err", DoubleType(), True),
        StructField("z_2Gausig", DoubleType(), True),
        StructField("z_2Ell", DoubleType(), True),
        StructField("z_2PA", DoubleType(), True),
        StructField("z_2ErrBits", IntegerType(), True),
        StructField("z_2AverageConf", DoubleType(), True),
        StructField("z_2Class", ShortType(), True),
        StructField("z_2ClassStat", DoubleType(), True),
        StructField("z_2ppErrBits", IntegerType(), True),
        StructField("z_2SeqNum", IntegerType(), True),
        StructField("z_2Xi", DoubleType(), True),
        StructField("z_2Eta", DoubleType(), True),
        StructField("yMjd", DoubleType(), True),
        StructField("yAperMag1", DoubleType(), True),
        StructField("yAperMag1Err", DoubleType(), True),
        StructField("yAperMag3", DoubleType(), True),
        StructField("yAperMag3Err", DoubleType(), True),
        StructField("yAperMag4", DoubleType(), True),
        StructField("yAperMag4Err", DoubleType(), True),
        StructField("yGausig", DoubleType(), True),
        StructField("yEll", DoubleType(), True),
        StructField("yPA", DoubleType(), True),
        StructField("yErrBits", IntegerType(), True),
        StructField("yAverageConf", DoubleType(), True),
        StructField("yClass", ShortType(), True),
        StructField("yClassStat", DoubleType(), True),
        StructField("yppErrBits", IntegerType(), True),
        StructField("ySeqNum", IntegerType(), True),
        StructField("yXi", DoubleType(), True),
        StructField("yEta", DoubleType(), True),
        StructField("y_1Mjd", DoubleType(), True),
        StructField("y_1AperMag1", DoubleType(), True),
        StructField("y_1AperMag1Err", DoubleType(), True),
        StructField("y_1AperMag3", DoubleType(), True),
        StructField("y_1AperMag3Err", DoubleType(), True),
        StructField("y_1AperMag4", DoubleType(), True),
        StructField("y_1AperMag4Err", DoubleType(), True),
        StructField("y_1Gausig", DoubleType(), True),
        StructField("y_1Ell", DoubleType(), True),
        StructField("y_1PA", DoubleType(), True),
        StructField("y_1ErrBits", IntegerType(), True),
        StructField("y_1AverageConf", DoubleType(), True),
        StructField("y_1Class", ShortType(), True),
        StructField("y_1ClassStat", DoubleType(), True),
        StructField("y_1ppErrBits", IntegerType(), True),
        StructField("y_1SeqNum", IntegerType(), True),
        StructField("y_1Xi", DoubleType(), True),
        StructField("y_1Eta", DoubleType(), True),
        StructField("y_2Mjd", DoubleType(), True),
        StructField("y_2AperMag1", DoubleType(), True),
        StructField("y_2AperMag1Err", DoubleType(), True),
        StructField("y_2AperMag3", DoubleType(), True),
        StructField("y_2AperMag3Err", DoubleType(), True),
        StructField("y_2AperMag4", DoubleType(), True),
        StructField("y_2AperMag4Err", DoubleType(), True),
        StructField("y_2Gausig", DoubleType(), True),
        StructField("y_2Ell", DoubleType(), True),
        StructField("y_2PA", DoubleType(), True),
        StructField("y_2ErrBits", IntegerType(), True),
        StructField("y_2AverageConf", DoubleType(), True),
        StructField("y_2Class", ShortType(), True),
        StructField("y_2ClassStat", DoubleType(), True),
        StructField("y_2ppErrBits", IntegerType(), True),
        StructField("y_2SeqNum", IntegerType(), True),
        StructField("y_2Xi", DoubleType(), True),
        StructField("y_2Eta", DoubleType(), True),
        StructField("jMjd", DoubleType(), True),
        StructField("jAperMag1", DoubleType(), True),
        StructField("jAperMag1Err", DoubleType(), True),
        StructField("jAperMag3", DoubleType(), True),
        StructField("jAperMag3Err", DoubleType(), True),
        StructField("jAperMag4", DoubleType(), True),
        StructField("jAperMag4Err", DoubleType(), True),
        StructField("jGausig", DoubleType(), True),
        StructField("jEll", DoubleType(), True),
        StructField("jPA", DoubleType(), True),
        StructField("jErrBits", IntegerType(), True),
        StructField("jAverageConf", DoubleType(), True),
        StructField("jClass", ShortType(), True),
        StructField("jClassStat", DoubleType(), True),
        StructField("jppErrBits", IntegerType(), True),
        StructField("jSeqNum", IntegerType(), True),
        StructField("jXi", DoubleType(), True),
        StructField("jEta", DoubleType(), True),
        StructField("j_1Mjd", DoubleType(), True),
        StructField("j_1AperMag1", DoubleType(), True),
        StructField("j_1AperMag1Err", DoubleType(), True),
        StructField("j_1AperMag3", DoubleType(), True),
        StructField("j_1AperMag3Err", DoubleType(), True),
        StructField("j_1AperMag4", DoubleType(), True),
        StructField("j_1AperMag4Err", DoubleType(), True),
        StructField("j_1Gausig", DoubleType(), True),
        StructField("j_1Ell", DoubleType(), True),
        StructField("j_1PA", DoubleType(), True),
        StructField("j_1ErrBits", IntegerType(), True),
        StructField("j_1AverageConf", DoubleType(), True),
        StructField("j_1Class", ShortType(), True),
        StructField("j_1ClassStat", DoubleType(), True),
        StructField("j_1ppErrBits", IntegerType(), True),
        StructField("j_1SeqNum", IntegerType(), True),
        StructField("j_1Xi", DoubleType(), True),
        StructField("j_1Eta", DoubleType(), True),
        StructField("j_2Mjd", DoubleType(), True),
        StructField("j_2AperMag1", DoubleType(), True),
        StructField("j_2AperMag1Err", DoubleType(), True),
        StructField("j_2AperMag3", DoubleType(), True),
        StructField("j_2AperMag3Err", DoubleType(), True),
        StructField("j_2AperMag4", DoubleType(), True),
        StructField("j_2AperMag4Err", DoubleType(), True),
        StructField("j_2Gausig", DoubleType(), True),
        StructField("j_2Ell", DoubleType(), True),
        StructField("j_2PA", DoubleType(), True),
        StructField("j_2ErrBits", IntegerType(), True),
        StructField("j_2AverageConf", DoubleType(), True),
        StructField("j_2Class", ShortType(), True),
        StructField("j_2ClassStat", DoubleType(), True),
        StructField("j_2ppErrBits", IntegerType(), True),
        StructField("j_2SeqNum", IntegerType(), True),
        StructField("j_2Xi", DoubleType(), True),
        StructField("j_2Eta", DoubleType(), True),
        StructField("hMjd", DoubleType(), True),
        StructField("hAperMag1", DoubleType(), True),
        StructField("hAperMag1Err", DoubleType(), True),
        StructField("hAperMag3", DoubleType(), True),
        StructField("hAperMag3Err", DoubleType(), True),
        StructField("hAperMag4", DoubleType(), True),
        StructField("hAperMag4Err", DoubleType(), True),
        StructField("hGausig", DoubleType(), True),
        StructField("hEll", DoubleType(), True),
        StructField("hPA", DoubleType(), True),
        StructField("hErrBits", IntegerType(), True),
        StructField("hAverageConf", DoubleType(), True),
        StructField("hClass", ShortType(), True),
        StructField("hClassStat", DoubleType(), True),
        StructField("hppErrBits", IntegerType(), True),
        StructField("hSeqNum", IntegerType(), True),
        StructField("hXi", DoubleType(), True),
        StructField("hEta", DoubleType(), True),
        StructField("h_1Mjd", DoubleType(), True),
        StructField("h_1AperMag1", DoubleType(), True),
        StructField("h_1AperMag1Err", DoubleType(), True),
        StructField("h_1AperMag3", DoubleType(), True),
        StructField("h_1AperMag3Err", DoubleType(), True),
        StructField("h_1AperMag4", DoubleType(), True),
        StructField("h_1AperMag4Err", DoubleType(), True),
        StructField("h_1Gausig", DoubleType(), True),
        StructField("h_1Ell", DoubleType(), True),
        StructField("h_1PA", DoubleType(), True),
        StructField("h_1ErrBits", IntegerType(), True),
        StructField("h_1AverageConf", DoubleType(), True),
        StructField("h_1Class", ShortType(), True),
        StructField("h_1ClassStat", DoubleType(), True),
        StructField("h_1ppErrBits", IntegerType(), True),
        StructField("h_1SeqNum", IntegerType(), True),
        StructField("h_1Xi", DoubleType(), True),
        StructField("h_1Eta", DoubleType(), True),
        StructField("h_2Mjd", DoubleType(), True),
        StructField("h_2AperMag1", DoubleType(), True),
        StructField("h_2AperMag1Err", DoubleType(), True),
        StructField("h_2AperMag3", DoubleType(), True),
        StructField("h_2AperMag3Err", DoubleType(), True),
        StructField("h_2AperMag4", DoubleType(), True),
        StructField("h_2AperMag4Err", DoubleType(), True),
        StructField("h_2Gausig", DoubleType(), True),
        StructField("h_2Ell", DoubleType(), True),
        StructField("h_2PA", DoubleType(), True),
        StructField("h_2ErrBits", IntegerType(), True),
        StructField("h_2AverageConf", DoubleType(), True),
        StructField("h_2Class", ShortType(), True),
        StructField("h_2ClassStat", DoubleType(), True),
        StructField("h_2ppErrBits", IntegerType(), True),
        StructField("h_2SeqNum", IntegerType(), True),
        StructField("h_2Xi", DoubleType(), True),
        StructField("h_2Eta", DoubleType(), True),
        StructField("ksMjd", DoubleType(), True),
        StructField("ksAperMag1", DoubleType(), True),
        StructField("ksAperMag1Err", DoubleType(), True),
        StructField("ksAperMag3", DoubleType(), True),
        StructField("ksAperMag3Err", DoubleType(), True),
        StructField("ksAperMag4", DoubleType(), True),
        StructField("ksAperMag4Err", DoubleType(), True),
        StructField("ksGausig", DoubleType(), True),
        StructField("ksEll", DoubleType(), True),
        StructField("ksPA", DoubleType(), True),
        StructField("ksErrBits", IntegerType(), True),
        StructField("ksAverageConf", DoubleType(), True),
        StructField("ksClass", ShortType(), True),
        StructField("ksClassStat", DoubleType(), True),
        StructField("ksppErrBits", IntegerType(), True),
        StructField("ksSeqNum", IntegerType(), True),
        StructField("ksXi", DoubleType(), True),
        StructField("ksEta", DoubleType(), True),
        StructField("ks_1Mjd", DoubleType(), True),
        StructField("ks_1AperMag1", DoubleType(), True),
        StructField("ks_1AperMag1Err", DoubleType(), True),
        StructField("ks_1AperMag3", DoubleType(), True),
        StructField("ks_1AperMag3Err", DoubleType(), True),
        StructField("ks_1AperMag4", DoubleType(), True),
        StructField("ks_1AperMag4Err", DoubleType(), True),
        StructField("ks_1Gausig", DoubleType(), True),
        StructField("ks_1Ell", DoubleType(), True),
        StructField("ks_1PA", DoubleType(), True),
        StructField("ks_1ErrBits", IntegerType(), True),
        StructField("ks_1AverageConf", DoubleType(), True),
        StructField("ks_1Class", ShortType(), True),
        StructField("ks_1ClassStat", DoubleType(), True),
        StructField("ks_1ppErrBits", IntegerType(), True),
        StructField("ks_1SeqNum", IntegerType(), True),
        StructField("ks_1Xi", DoubleType(), True),
        StructField("ks_1Eta", DoubleType(), True),
        StructField("ks_2Mjd", DoubleType(), True),
        StructField("ks_2AperMag1", DoubleType(), True),
        StructField("ks_2AperMag1Err", DoubleType(), True),
        StructField("ks_2AperMag3", DoubleType(), True),
        StructField("ks_2AperMag3Err", DoubleType(), True),
        StructField("ks_2AperMag4", DoubleType(), True),
        StructField("ks_2AperMag4Err", DoubleType(), True),
        StructField("ks_2Gausig", DoubleType(), True),
        StructField("ks_2Ell", DoubleType(), True),
        StructField("ks_2PA", DoubleType(), True),
        StructField("ks_2ErrBits", IntegerType(), True),
        StructField("ks_2AverageConf", DoubleType(), True),
        StructField("ks_2Class", ShortType(), True),
        StructField("ks_2ClassStat", DoubleType(), True),
        StructField("ks_2ppErrBits", IntegerType(), True),
        StructField("ks_2SeqNum", IntegerType(), True),
        StructField("ks_2Xi", DoubleType(), True),
        StructField("ks_2Eta", DoubleType(), True),
        StructField("hEpochMjd", ArrayType(DoubleType(), True), True),
        StructField("jEpochMjd", ArrayType(DoubleType(), True), True),
        StructField("ksEpochMjd", ArrayType(DoubleType(), True), True),
        StructField("yEpochMjd", ArrayType(DoubleType(), True), True),
        StructField("zEpochMjd", ArrayType(DoubleType(), True), True),
        StructField("hEpochAperMag1", ArrayType(FloatType(), True), True),
        StructField("jEpochAperMag1", ArrayType(FloatType(), True), True),
        StructField("ksEpochAperMag1", ArrayType(FloatType(), True), True),
        StructField("yEpochAperMag1", ArrayType(FloatType(), True), True),
        StructField("zEpochAperMag1", ArrayType(FloatType(), True), True),
        StructField("hEpochAperMag1err", ArrayType(FloatType(), True), True),
        StructField("jEpochAperMag1err", ArrayType(FloatType(), True), True),
        StructField("ksEpochAperMag1err", ArrayType(FloatType(), True), True),
        StructField("yEpochAperMag1err", ArrayType(FloatType(), True), True),
        StructField("zEpochAperMag1err", ArrayType(FloatType(), True), True),
        StructField("hEpochAperMag2", ArrayType(FloatType(), True), True),
        StructField("jEpochAperMag2", ArrayType(FloatType(), True), True),
        StructField("ksEpochAperMag2", ArrayType(FloatType(), True), True),
        StructField("yEpochAperMag2", ArrayType(FloatType(), True), True),
        StructField("zEpochAperMag2", ArrayType(FloatType(), True), True),
        StructField("hEpochAperMag2err", ArrayType(FloatType(), True), True),
        StructField("jEpochAperMag2err", ArrayType(FloatType(), True), True),
        StructField("ksEpochAperMag2err", ArrayType(FloatType(), True), True),
        StructField("yEpochAperMag2err", ArrayType(FloatType(), True), True),
        StructField("zEpochAperMag2err", ArrayType(FloatType(), True), True),
        StructField("hEpochAperMag3", ArrayType(FloatType(), True), True),
        StructField("jEpochAperMag3", ArrayType(FloatType(), True), True),
        StructField("ksEpochAperMag3", ArrayType(FloatType(), True), True),
        StructField("yEpochAperMag3", ArrayType(FloatType(), True), True),
        StructField("zEpochAperMag3", ArrayType(FloatType(), True), True),
        StructField("hEpochAperMag3err", ArrayType(FloatType(), True), True),
        StructField("jEpochAperMag3err", ArrayType(FloatType(), True), True),
        StructField("ksEpochAperMag3err", ArrayType(FloatType(), True), True),
        StructField("yEpochAperMag3err", ArrayType(FloatType(), True), True),
        StructField("zEpochAperMag3err", ArrayType(FloatType(), True), True),
        StructField("hEpochErrBits", ArrayType(IntegerType(), True), True),
        StructField("jEpochErrBits", ArrayType(IntegerType(), True), True),
        StructField("ksEpochErrBits", ArrayType(IntegerType(), True), True),
        StructField("yEpochErrBits", ArrayType(IntegerType(), True), True),
        StructField("zEpochErrBits", ArrayType(IntegerType(), True), True),
        StructField("hEpochAverageConf", ArrayType(FloatType(), True), True),
        StructField("jEpochAverageConf", ArrayType(FloatType(), True), True),
        StructField("ksEpochAverageConf", ArrayType(FloatType(), True), True),
        StructField("yEpochAverageConf", ArrayType(FloatType(), True), True),
        StructField("zEpochAverageConf", ArrayType(FloatType(), True), True),
        StructField("hEpochClass", ArrayType(ShortType(), True), True),
        StructField("jEpochClass", ArrayType(ShortType(), True), True),
        StructField("ksEpochClass", ArrayType(ShortType(), True), True),
        StructField("yEpochClass", ArrayType(ShortType(), True), True),
        StructField("zEpochClass", ArrayType(ShortType(), True), True),
        StructField("hEpochClassStat", ArrayType(FloatType(), True), True),
        StructField("jEpochClassStat", ArrayType(FloatType(), True), True),
        StructField("ksEpochClassStat", ArrayType(FloatType(), True), True),
        StructField("yEpochClassStat", ArrayType(FloatType(), True), True),
        StructField("zEpochClassStat", ArrayType(FloatType(), True), True),
        StructField("hEpochDeprecated", ArrayType(ShortType(), True), True),
        StructField("jEpochDeprecated", ArrayType(ShortType(), True), True),
        StructField("ksEpochDeprecated", ArrayType(ShortType(), True), True),
        StructField("yEpochDeprecated", ArrayType(ShortType(), True), True),
        StructField("zEpochDeprecated", ArrayType(ShortType(), True), True),
        StructField("hEpochPpErrBits", ArrayType(FloatType(), True), True),
        StructField("jEpochPpErrBits", ArrayType(FloatType(), True), True),
        StructField("ksEpochPpErrBits", ArrayType(FloatType(), True), True),
        StructField("yEpochPpErrBits", ArrayType(FloatType(), True), True),
        StructField("zEpochPpErrBits", ArrayType(FloatType(), True), True),
        StructField("hEpochObjID", ArrayType(IntegerType(), True), True),
        StructField("jEpochObjID", ArrayType(IntegerType(), True), True),
        StructField("ksEpochObjID", ArrayType(IntegerType(), True), True),
        StructField("yEpochObjID", ArrayType(IntegerType(), True), True),
        StructField("zEpochObjID", ArrayType(IntegerType(), True), True),
        StructField("hEpochMultiframeID", ArrayType(LongType(), True), True),
        StructField("jEpochMultiframeID", ArrayType(LongType(), True), True),
        StructField("ksEpochMultiframeID", ArrayType(LongType(), True), True),
        StructField("yEpochMultiframeID", ArrayType(LongType(), True), True),
        StructField("zEpochMultiframeID", ArrayType(LongType(), True), True),
        StructField("hEpochExtNum", ArrayType(ShortType(), True), True),
        StructField("jEpochExtNum", ArrayType(ShortType(), True), True),
        StructField("ksEpochExtNum", ArrayType(ShortType(), True), True),
        StructField("yEpochExtNum", ArrayType(ShortType(), True), True),
        StructField("zEpochExtNum", ArrayType(ShortType(), True), True),
        StructField("hEpochSeqNum", ArrayType(IntegerType(), True), True),
        StructField("jEpochSeqNum", ArrayType(IntegerType(), True), True),
        StructField("ksEpochSeqNum", ArrayType(IntegerType(), True), True),
        StructField("yEpochSeqNum", ArrayType(IntegerType(), True), True),
        StructField("zEpochSeqNum", ArrayType(IntegerType(), True), True),
        StructField("hEpochFlag", ArrayType(ShortType(), True), True),
        StructField("jEpochFlag", ArrayType(ShortType(), True), True),
        StructField("ksEpochFlag", ArrayType(ShortType(), True), True),
        StructField("yEpochFlag", ArrayType(ShortType(), True), True),
        StructField("zEpochFlag", ArrayType(ShortType(), True), True),
        StructField("hEpochModelDistSecs", ArrayType(FloatType(), True), True),
        StructField("jEpochModelDistSecs", ArrayType(FloatType(), True), True),
        StructField("ksEpochModelDistSecs", ArrayType(FloatType(), True), True),
        StructField("yEpochModelDistSecs", ArrayType(FloatType(), True), True),
        StructField("zEpochModelDistSecs", ArrayType(FloatType(), True), True),
    ]
)
