---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
spec:
  selector:
    app: hive
  ports:
    - port: 9083
      targetPort: 9083

---
apiVersion: v1
kind: Service
metadata:
  name: dagster
spec:
  selector:
    app: dagster
  ports:
    - port: {{ .Values.dagster.port }}
      targetPort: {{ .Values.dagster.port }}
