# Generated by Django 5.2.4 on 2025-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_alter_executesql_user_anonymousquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='executesql',
            name='schema',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
