# Generated by Django 5.2.4 on 2025-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_executesql_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='executesql',
            name='num_rows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
