# Generated by Django 5.2.4 on 2025-12-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_executesql_num_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(blank=True, max_length=63, null=True)),
                ('access', models.CharField(choices=[('PUBLIC', 'Public'), ('PROPRIETARY', 'Proprietary')], max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='QueryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('query', models.TextField()),
                ('schema', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
