services:

  auth:
    restart: always
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.12.0
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://cilogon.org
      - OAUTH2_PROXY_CLIENT_ID=${OIDC_RP_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OIDC_RP_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL=true
      - OAUTH2_PROXY_HTTP_ADDRESS=http://0.0.0.0:4180
      - OAUTH2_PROXY_WHITELIST_DOMAINS=${DOMAIN}
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OUATH2_PROXY_SHOW_DEBUG_ON_ERROR=true
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_AUTH_LOGGING=true
      - OAUTH2_PROXY_STANDARD_LOGGING=true
      - OAUTH2_PROXY_REQUEST_LOGGING=true
      - OAUTH2_PROXY_SCOPE = "openid email profile"
    # ports:
    #   - 4180:4180

  proxy:
    restart: always
    image: caddy
    volumes:
      - ./server/:/app
      - ./docker/${DEPLOYMENT}/caddy/Caddyfile/:/etc/caddy/Caddyfile
    ports:
      - 9000:80
      - 9443:443

  web:
    restart: always
    build:
      context: .
      dockerfile: ./docker/${DEPLOYMENT}/django/Dockerfile
    image: django_celery
    command: /start
    volumes:
      - ./server/:/app
    # ports:
    #   - 9000:8000
    env_file:
      - ./.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy

  db:
    restart: always
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    restart: always
    image: rabbitmq:3
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10

  celery_worker:
    restart: always
    build:
      context: .
      dockerfile: ./docker/${DEPLOYMENT}/django/Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - ./server/:/app
    env_file:
      - ./.env
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy

  celery_beat:
    restart: always
    build:
      context: .
      dockerfile: ./docker/${DEPLOYMENT}/django/Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - ./server/:/app
    env_file:
      - ./.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy

  # flower:
  #   build:
  #     context: .
  #     dockerfile: ./docker/${DEPLOYMENT}/django/Dockerfile
  #   image: django_celery_example_celery_flower
  #   command: /start-flower
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - redis
  #     - db

volumes:
  postgres_data: