# Generated by Django 5.2.4 on 2026-07-23 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQLGenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Completed successfully'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('prompt', models.TextField()),
                ('data_release', models.CharField(blank=True, max_length=255, null=True)),
                ('tables', models.JSONField(default=list)),
                ('generated_sql', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
