"""
Django settings for moons project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# generate with `python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'`
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', False)

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split()

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'mozilla_django_oidc',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    'django_tables2',
    'crispy_forms',
    'crispy_bootstrap5',
    'core',
    'queries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mozilla_django_oidc.middleware.SessionRefresh',
]

ROOT_URLCONF = 'moons.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moons.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_DATABASE', os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT")
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-gb'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

CELERY_TIMEZONE = 'Europe/London'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 10800
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER")

DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5.html"

LOCAL_FILE_DIR = BASE_DIR / 'files' / 'moons-web'
QUERY_DATABASE = {
    'CONNECTION_STRING': os.environ.get('QUERY_DB_CONNECTION', 'file:///app/resources/mock-gesiDR5.sqlite3'),
    'DRIVER': os.environ.get('QUERY_DB_DRIVER', 'adbc_driver_sqlite.dbapi'),
    # 'CONNECTION_STRING': 'postgresql://postgres:12345@localhost:5432/',
    # 'DRIVER': 'adbc_driver_postgresql.dbapi',
}

SCHEMA_FILES = [
    BASE_DIR / 'resources' / 'GES' / 'GES_CurationLogsSchema.json',
    BASE_DIR / 'resources' / 'GES' / 'GES_ErrorLogsSchema.json',
    BASE_DIR / 'resources' / 'GES' / 'GES_NeighboursSchema.json',
    BASE_DIR / 'resources' / 'GES' / 'GES_SpectrumSchema.json',
    BASE_DIR / 'resources' / 'GES' / 'GES_Views.json',
]

OIDC_RP_CLIENT_ID = os.environ['OIDC_RP_CLIENT_ID']
OIDC_RP_CLIENT_SECRET = os.environ['OIDC_RP_CLIENT_SECRET']
# OIDC_OP_AUTHORIZATION_ENDPOINT = "https://iris-iam.stfc.ac.uk/authorize"
# OIDC_OP_TOKEN_ENDPOINT = "https://iris-iam.stfc.ac.uk/token"
# OIDC_OP_JWKS_ENDPOINT = 'https://iris-iam.stfc.ac.uk/jwk'
# OIDC_OP_USER_ENDPOINT = "https://iris-iam.stfc.ac.uk/userinfo"
# OIDC_RP_SCOPES = 'openid profile email'
OIDC_OP_AUTHORIZATION_ENDPOINT = "https://cilogon.org/authorize"
OIDC_OP_TOKEN_ENDPOINT = "https://cilogon.org/oauth2/token"
OIDC_OP_JWKS_ENDPOINT = "https://cilogon.org/oauth2/certs"
OIDC_OP_USER_ENDPOINT = "https://cilogon.org/oauth2/userinfo"
OIDC_RP_SCOPES = 'openid profile email org.cilogon.userinfo'
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_CREATE_USER = False
